package com.im.mall.model.dao;

import com.im.mall.model.pojo.Cart;
import com.im.mall.model.pojo.Product;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_cart
     *
     * @mbg.generated Sat Sep 04 17:20:20 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_cart
     *
     * @mbg.generated Sat Sep 04 17:20:20 CST 2021
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_cart
     *
     * @mbg.generated Sat Sep 04 17:20:20 CST 2021
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_cart
     *
     * @mbg.generated Sat Sep 04 17:20:20 CST 2021
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_cart
     *
     * @mbg.generated Sat Sep 04 17:20:20 CST 2021
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_cart
     *
     * @mbg.generated Sat Sep 04 17:20:20 CST 2021
     */
    int updateByPrimaryKey(Cart record);

}