package com.im.mall.model.dao;

import com.im.mall.model.pojo.Order;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int updateByPrimaryKey(Order record);
}