package com.im.mall.model.dao;

import com.im.mall.model.pojo.OrderItem;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order_item
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order_item
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order_item
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order_item
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order_item
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order_item
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int updateByPrimaryKey(OrderItem record);
}