package com.im.mall.model.dao;

import com.im.mall.model.pojo.OrderItem;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order_item
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order_item
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order_item
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order_item
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order_item
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_order_item
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int updateByPrimaryKey(OrderItem record);
}