package com.im.mall.model.dao;

import com.im.mall.model.pojo.Product;
import com.im.mall.model.query.ProductListQuery;
import org.springframework.data.repository.query.Param;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_product
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_product
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_product
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_product
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_product
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_product
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int updateByPrimaryKey(Product record);


    Product selectByName(String name);
    // 参数与myBatis 相关需要加上@param
    int batchUpdateSellStatus(@Param("ids") Integer[] ids, @Param("sellStatus") Integer sellStatus);
    // 查所有的商品
    List<Product> selectListForAdmin();

    List<Product> selectList( @Param("query") ProductListQuery query);

}