package com.im.mall.model.dao;

import com.im.mall.model.pojo.Product;
import org.springframework.stereotype.Repository;

@Repository
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_product
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_product
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_product
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_product
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_product
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_product
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    int updateByPrimaryKey(Product record);
}