package com.im.mall.model.dao;

import com.im.mall.model.pojo.User;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_user
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_user
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_user
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_user
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_user
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imooc_mall_user
     *
     * @mbg.generated Sat Sep 04 17:20:21 CST 2021
     */
    int updateByPrimaryKey(User record);

    User selectByName(String userName);

    User selectLogin(@Param("userName") String userName, @Param("password") String password);
}