package com.im.mall.model.pojo;

import java.util.Date;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imooc_mall_category.id
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    private Integer id;

    private String name;

    private Integer type;

    private Integer parentId;

    private Integer orderNum;

    private Date createTime;

    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imooc_mall_category.type
     *
     * @return the value of imooc_mall_category.type
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imooc_mall_category.type
     *
     * @param type the value for imooc_mall_category.type
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imooc_mall_category.parent_id
     *
     * @return the value of imooc_mall_category.parent_id
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imooc_mall_category.parent_id
     *
     * @param parentId the value for imooc_mall_category.parent_id
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imooc_mall_category.order_num
     *
     * @return the value of imooc_mall_category.order_num
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imooc_mall_category.order_num
     *
     * @param orderNum the value for imooc_mall_category.order_num
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imooc_mall_category.create_time
     *
     * @return the value of imooc_mall_category.create_time
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imooc_mall_category.create_time
     *
     * @param createTime the value for imooc_mall_category.create_time
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imooc_mall_category.update_time
     *
     * @return the value of imooc_mall_category.update_time
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imooc_mall_category.update_time
     *
     * @param updateTime the value for imooc_mall_category.update_time
     *
     * @mbg.generated Fri Aug 20 18:45:29 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}